<h1><font color='blue'>Análise de Sentimentos e Sistemas de Recomendação</font></h1>
<h2><b>Prática U2-T3-V1.2-Recomendação baseada em conteúdo</b></h2>


---

# Exemplo 1 - Recomendação baseada em conteúdo (não personalizada)

## Lendo o dataset de filmes

In [22]:
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)
warnings.filterwarnings("ignore", category=UserWarning)

In [23]:
import pandas as pd
import numpy as np

movies = pd.read_csv('https://drive.google.com/uc?export=download&id=1yjGdaAJ5-YgIUx_1mLTcPqiZ8OI9TeqH', encoding='latin-1', low_memory=False)
movies['tags'] = movies['tags'].apply(lambda x: '' if isinstance(x,float) else x)
movies.set_index('movieId', inplace=True)
movies.head()

,title,genres,tags,tag_count,vote_count,vote_average,imdb_score
movieId,,,,,,,
1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,fun pixar,2,215,3.920930,3.894473
2,Jumanji,Adventure|Children|Fantasy,fantasy magic_board_game game robin_williams,4,110,3.431818,3.419009
3,Grumpier Old Men,Comedy|Romance,old moldy,2,52,3.259615,3.260033
4,Waiting to Exhale,Comedy|Drama|Romance,,0,7,2.357143,2.866377
5,Father of the Bride Part II,Comedy,pregnancy remake,2,49,3.071429,3.101070

Formatando a lista de documentos

In [24]:
# Baixar recursos do NLTK
import nltk
nltk.download("punkt")
nltk.download("punkt_tab")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

Criar função para tokenizar, normalizar para minúsculos e remover caracteres especiais

In [25]:
import re
from nltk.tokenize import word_tokenize
import unicodedata

def preprocess(text):
    text = text.lower()
    text = unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode("utf-8")
    text = re.sub(r'[^a-z0-9\s]', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()
    tokens = word_tokenize(text)
    return tokens

In [26]:
def retorna_documentos(df):
    documentos = []
    for title, genres, tags in df[['title', 'genres', 'tags']].values:
        lista = genres.split('|')
        documentos.append(' '.join(preprocess(title.lower() + ' ' + ' '.join(lista).lower() + ' ' + tags)))
    return documentos

documentos = retorna_documentos(movies)
documentos[:5]

['toy story adventure animation children comedy fantasy fun pixar',
 'jumanji adventure children fantasy fantasy magic board game game robin williams',
 'grumpier old men comedy romance old moldy',
 'waiting to exhale comedy drama romance',
 'father of the bride part ii comedy pregnancy remake']

## Representando filmes como *embeddings*

### Criando os embeddings dos documentos

Vamos usar uma implementação prática da estratégia **SBERT (Sentence-BERT)** para a geração dos *embeddings*. O **SBERT** é uma modificação do BERT treinada para gerar embeddings de frases/documentos que podem ser comparados diretamente via similaridade de cosseno.

In [27]:
from sentence_transformers import SentenceTransformer, util

model = SentenceTransformer('all-MiniLM-L6-v2')

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Converter documentos para *embeddings*

In [28]:
embeddings = model.encode(documentos, normalize_embeddings=True)
print(embeddings.shape)

(9724, 384)

In [29]:
embeddings[0]

array([-5.19503318e-02,  8.96416837e-04,  1.36910640e-02, -1.78741980e-02,
       -5.73252290e-02,  1.23114204e-02,  1.00211255e-01, -2.27374006e-02,
        1.65828094e-02,  6.23797299e-03,  1.19955409e-02, -1.23948352e-02,
        2.36282474e-03,  7.46658817e-02,  1.62983965e-02,  1.64942443e-02,
        4.44534831e-02,  4.08788361e-02,  9.35138389e-02, -7.51637369e-02,
        6.62237704e-02,  3.65036912e-03,  6.79250360e-02, -2.06108484e-02,
       -5.57867959e-02,  4.09747213e-02, -3.15521075e-03, -3.03457137e-02,
       -3.62760499e-02, -4.11853157e-02,  7.65422583e-02,  5.33682480e-02,
        1.81106683e-02, -3.64747569e-02,  1.25191836e-02,  4.91976365e-03,
        2.17597671e-02, -5.34348153e-02, -2.04926953e-02,  2.52218004e-02,
       -5.78783303e-02,  1.00279320e-02, -9.96980444e-03, -8.22473019e-02,
        5.69721917e-03, -5.05874911e-03, -3.84973958e-02, -8.74377191e-02,
        5.57347164e-02,  8.74505565e-02, -4.46493141e-02, -2.20414549e-02,
        2.30034553e-02,  1.17940269e-02,  3.67400050e-02,  2.28273906e-02,
       -9.68194753e-03, -6.16546795e-02,  6.43012896e-02, -3.21334265e-02,
       -5.03717698e-02,  3.71472863e-03,  1.35913212e-02,  2.94696968e-02,
       -4.24878970e-02, -1.21585079e-01, -7.30197877e-03, -3.32271978e-02,
       -3.05562746e-02, -7.23219737e-02, -1.01185933e-01, -1.91174969e-02,
        2.71946937e-02, -2.56121159e-02, -7.32416986e-03,  8.04408453e-03,
       -2.48813387e-02, -2.99836230e-02, -3.11957952e-02, -4.44417223e-02,
       -5.61842956e-02, -7.47905821e-02,  1.31311612e-02, -6.34204075e-02,
       -2.31250226e-02,  6.57488182e-02,  7.65184164e-02, -5.82658220e-03,
       -5.72131649e-02,  4.28733341e-02, -8.50319266e-02,  4.12184335e-02,
        1.18144281e-01,  1.01882838e-01, -5.25568426e-03, -2.64929626e-02,
       -1.52755408e-02, -1.22804724e-01, -4.12978530e-02, -9.75745823e-03,
        2.80635916e-02, -4.58783247e-02,  8.93613100e-02, -2.26088185e-02,
        3.66683081e-02,  2.20386162e-02,  6.36556558e-03, -6.79536760e-02,
        6.57782853e-02,  6.16708724e-03,  3.91833346e-05, -1.26407202e-02,
        2.64605731e-02,  2.78602578e-02,  8.07589199e-03, -6.10697977e-02,
        9.62445885e-03, -3.45456749e-02,  5.88295748e-03,  1.37898922e-02,
        1.62157729e-01,  3.17511708e-02,  8.43091868e-03,  2.64725238e-02,
        8.42643494e-04, -5.47748394e-02, -4.37472276e-02,  4.01155998e-33,
       -8.40970594e-03,  2.71501932e-02,  1.90824214e-02,  1.83543954e-02,
        1.02935340e-02,  4.10132334e-02,  1.45219779e-02, -2.14187684e-03,
       -9.35434476e-02, -9.02605522e-03, -1.25950262e-01,  4.45920862e-02,
       -1.12567149e-01, -6.29097922e-03,  9.20604263e-03, -4.00996469e-02,
       -1.15599640e-01, -2.48985030e-02,  6.48340359e-02,  4.86098528e-02,
       -3.96385603e-02,  5.98092712e-02, -1.73110478e-02,  3.08870953e-02,
       -2.25143898e-02,  4.61488552e-02, -1.35452664e-02, -4.68561500e-02,
        4.66044582e-02,  1.86407492e-02,  6.78440509e-03, -1.41802914e-02,
        1.64903775e-02, -9.58835427e-03,  4.78301756e-02, -3.98965366e-02,
        3.29577550e-02, -5.09876385e-02, -5.05022109e-02,  1.03804767e-01,
        6.53575361e-02, -9.84638929e-02, -7.68008903e-02,  8.84872153e-02,
       -3.35830189e-02,  1.58707071e-02,  7.46258497e-02, -2.69011520e-02,
       -5.36268763e-02,  1.05197676e-01, -3.84064354e-02,  1.76779907e-02,
       -5.42819090e-02, -8.46284181e-02, -3.38035114e-02, -4.70563024e-03,
        1.03044044e-02, -5.64914793e-02, -7.18253758e-03, -2.95739789e-02,
        1.06282517e-01,  3.74899916e-02,  4.68223654e-02, -6.04043491e-02,
       -5.00055030e-03,  2.38911975e-02,  1.31480828e-01, -3.89276328e-03,
        4.60241288e-02,  1.74435806e-02,  2.05952320e-02,  3.60550918e-02,
        9.18791369e-02, -6.16800524e-02,  4.48270589e-02, -1.76441986e-02,
       -4.05909680e-02, -1.60279721e-02, -9.43726748e-02, -1.88189670e-02,
        1.15899686e-02, -1.98652372e-02, -6.94554597e-02,  1.79333817e-02,
       -1.66502930e-02, -1.37450978e-01,  1.88496727e-02,  3.67725326e-04,
       -1.77938654e-03,  1.95621746e-03, -2.89017893e-02, -7.72993267e-02,
        1.47037031e-02,  1.96735151e-02,  3.75639647e-02, -5.02136914e-33,
        2.65440214e-02, -6.02014400e-02, -8.22282955e-02,  6.31354889e-03,
        5.31471595e-02,  1.81801300e-02,  1.98360696e-03,  3.47932316e-02,
        5.63336723e-02,  1.89804770e-02, -6.83697611e-02,  4.04113047e-02,
        1.67988334e-02, -3.85184959e-02,  1.75089370e-02,  4.69551422e-03,
        4.92596179e-02, -2.38829181e-02,  9.91089642e-03,  2.42136717e-02,
        4.20739315e-02,  1.32923899e-02, -1.01762153e-01,  6.60063401e-02,
        4.98387329e-02,  9.43690613e-02,  2.89040208e-02, -5.38724326e-02,
       -3.80998403e-02,  8.24041292e-02, -2.48510446e-02, -5.46308570e-02,
        7.18040541e-02,  1.16898991e-01, -3.82298976e-02, -8.16497281e-02,
       -1.98103618e-02, -3.15300710e-02, -2.37901099e-02, -1.17660545e-01,
        6.87080389e-03, -7.71770924e-02, -1.47206411e-02,  6.28584996e-02,
       -1.70919728e-02, -2.12398488e-02, -4.86072293e-03,  3.39915715e-02,
        5.81587059e-03,  5.95387816e-02, -4.89262044e-02,  3.19775715e-02,
       -3.84087190e-02, -1.11940414e-01, -6.94526220e-03, -1.03560677e-02,
        1.46950241e-02, -3.06300018e-02,  6.30715042e-02,  7.17491433e-02,
        7.21437298e-03, -9.08693951e-03,  2.74718385e-02,  2.34067645e-02,
       -5.93747683e-02,  1.88850444e-02,  2.69553554e-03, -9.64754634e-03,
        4.66446159e-03, -2.87694149e-02,  3.93659249e-02,  1.16108410e-01,
        4.90929037e-02, -8.57380256e-02, -1.83496140e-02,  4.89566475e-02,
       -2.93299984e-02, -8.89622432e-04,  1.98750235e-02,  3.26356525e-03,
        1.11879371e-02, -3.72821651e-02,  5.84229315e-03,  5.33503890e-02,
       -6.99475929e-02, -1.83363247e-03, -5.38137108e-02,  2.52836682e-02,
       -3.69864777e-02,  4.25823331e-02,  6.75337464e-02,  9.77035686e-02,
        6.45314679e-02,  5.74671896e-03, -2.16813218e-02, -1.97127630e-08,
        1.05322478e-03, -1.61787483e-03, -3.42949964e-02, -9.42623317e-02,
        5.62253557e-02,  5.42417653e-02, -5.78284822e-02,  1.12741822e-02,
       -1.60324201e-02, -3.17541026e-02,  6.68044761e-02,  1.06565161e-02,
        8.25182348e-02,  6.81543574e-02,  5.59056848e-02,  5.61781600e-02,
        2.47671432e-03, -1.38680346e-03,  3.84884141e-02,  4.76195142e-02,
       -3.36111523e-02,  4.39393744e-02,  1.97872147e-02, -2.60501970e-02,
       -1.45048827e-01,  2.13356446e-02, -3.45038138e-02, -6.72633871e-02,
        2.34574694e-02,  5.89340143e-02,  5.13146520e-02,  4.40114737e-02,
       -7.79528618e-02, -2.24778894e-02, -3.93425003e-02, -1.01902388e-01,
       -3.55974361e-02,  2.14216076e-02, -2.02378770e-03, -2.58918814e-02,
        7.56045207e-02,  1.60239171e-02,  5.08798286e-02, -1.54697569e-02,
       -2.03186348e-02,  2.86256447e-02, -2.34653987e-02, -1.75464496e-01,
        6.12318814e-02,  4.23796587e-02, -5.63388355e-02, -1.40256425e-02,
       -1.17437735e-01,  5.27736219e-03,  8.32754523e-02, -3.70512670e-03,
       -1.51544735e-02,  7.14038208e-04, -7.97829852e-02,  4.86245379e-02,
        1.51975695e-02,  3.93462963e-02,  5.14321886e-02,  6.11302108e-02],
      dtype=float32)

## Recomendação de itens baseada em conteúdo

A partir dos *embeddings* gerados para cada documento, será possível executar consultas recuperando os documentos relevantes, de acordo com palavras chaves informadas pelo usuário.

Vamos usar a biblioteca **`hnswlib`** para executar uma busca vetorial rápida e eficiente baseada em grafos HNSW.

É muito usada em busca semântica com *embeddings* para encontrar os documentos mais similares em grandes coleções.

In [30]:
!pip install -qU hnswlib

Preparando o índice para a busca

In [31]:
import hnswlib

index = hnswlib.Index(space='cosine', dim=embeddings.shape[1])
index.init_index(max_elements=len(documentos))
index.add_items(embeddings)

### Encontrar filmes similares

In [32]:
ids = [1, 108932]
retorna_documentos(movies.query('movieId in ' + str(ids)))

['toy story adventure animation children comedy fantasy fun pixar',
 'the lego movie action adventure animation children comedy fantasy colorful feel good quirky fun clever cheeky imaginative']

Encontra os *embeddings* para os filmes

In [33]:
embeddings_query = model.encode(retorna_documentos(movies.query('movieId in ' + str(ids))))
embeddings_query

array([[-5.19503169e-02,  8.96431389e-04,  1.36910751e-02,
        -1.78742185e-02, -5.73252477e-02,  1.23114372e-02,
         1.00211255e-01, -2.27373838e-02,  1.65828001e-02,
         6.23796228e-03,  1.19955372e-02, -1.23948390e-02,
         2.36285292e-03,  7.46658742e-02,  1.62983779e-02,
         1.64942387e-02,  4.44534793e-02,  4.08788174e-02,
         9.35138315e-02, -7.51637891e-02,  6.62238002e-02,
         3.65038449e-03,  6.79250658e-02, -2.06108484e-02,
        -5.57868108e-02,  4.09747101e-02, -3.15523404e-03,
        -3.03457491e-02, -3.62760425e-02, -4.11853381e-02,
         7.65422508e-02,  5.33682778e-02,  1.81106627e-02,
        -3.64747755e-02,  1.25192199e-02,  4.91975714e-03,
         2.17597745e-02, -5.34348302e-02, -2.04926934e-02,
         2.52218265e-02, -5.78783229e-02,  1.00279097e-02,
        -9.96984169e-03, -8.22473168e-02,  5.69725130e-03,
        -5.05870767e-03, -3.84973623e-02, -8.74377117e-02,
         5.57346977e-02,  8.74505341e-02, -4.46493402e-02,
        -2.20414512e-02,  2.30034459e-02,  1.17939916e-02,
         3.67399827e-02,  2.28273869e-02, -9.68192518e-03,
        -6.16546609e-02,  6.43012896e-02, -3.21334116e-02,
        -5.03717810e-02,  3.71477893e-03,  1.35913538e-02,
         2.94697136e-02, -4.24878895e-02, -1.21585101e-01,
        -7.30195502e-03, -3.32272090e-02, -3.05562653e-02,
        -7.23219961e-02, -1.01185903e-01, -1.91174857e-02,
         2.71947011e-02, -2.56121196e-02, -7.32420105e-03,
         8.04408174e-03, -2.48812772e-02, -2.99836416e-02,
        -3.11958231e-02, -4.44417372e-02, -5.61842807e-02,
        -7.47905895e-02,  1.31311985e-02, -6.34203851e-02,
        -2.31250115e-02,  6.57488257e-02,  7.65184462e-02,
        -5.82655473e-03, -5.72131462e-02,  4.28732969e-02,
        -8.50319490e-02,  4.12184224e-02,  1.18144222e-01,
         1.01882845e-01, -5.25567820e-03, -2.64929440e-02,
        -1.52755417e-02, -1.22804701e-01, -4.12978604e-02,
        -9.75740980e-03,  2.80635767e-02, -4.58783284e-02,
         8.93613324e-02, -2.26088036e-02,  3.66683006e-02,
         2.20386144e-02,  6.36558002e-03, -6.79536685e-02,
         6.57782704e-02,  6.16710447e-03,  3.92108050e-05,
        -1.26407081e-02,  2.64605805e-02,  2.78602578e-02,
         8.07590224e-03, -6.10698089e-02,  9.62445326e-03,
        -3.45457383e-02,  5.88296633e-03,  1.37898596e-02,
         1.62157744e-01,  3.17511521e-02,  8.43090005e-03,
         2.64725350e-02,  8.42637673e-04, -5.47748171e-02,
        -4.37472276e-02,  4.01156145e-33, -8.40971060e-03,
         2.71501783e-02,  1.90824345e-02,  1.83543768e-02,
         1.02935219e-02,  4.10132222e-02,  1.45219993e-02,
        -2.14186241e-03, -9.35434699e-02, -9.02603101e-03,
        -1.25950292e-01,  4.45920788e-02, -1.12567157e-01,
        -6.29098434e-03,  9.20607708e-03, -4.00996618e-02,
        -1.15599640e-01, -2.48985216e-02,  6.48340434e-02,
         4.86098304e-02, -3.96385714e-02,  5.98092973e-02,
        -1.73110627e-02,  3.08870897e-02, -2.25143526e-02,
         4.61488590e-02, -1.35452747e-02, -4.68561761e-02,
         4.66044694e-02,  1.86407361e-02,  6.78440183e-03,
        -1.41802868e-02,  1.64903831e-02, -9.58831981e-03,
         4.78301868e-02, -3.98965590e-02,  3.29577364e-02,
        -5.09876423e-02, -5.05022258e-02,  1.03804782e-01,
         6.53575286e-02, -9.84638631e-02, -7.68008679e-02,
         8.84872302e-02, -3.35830376e-02,  1.58706866e-02,
         7.46258274e-02, -2.69011632e-02, -5.36268875e-02,
         1.05197646e-01, -3.84063981e-02,  1.76780429e-02,
        -5.42819016e-02, -8.46284330e-02, -3.38034779e-02,
        -4.70563583e-03,  1.03043746e-02, -5.64915016e-02,
        -7.18252175e-03, -2.95739602e-02,  1.06282510e-01,
         3.74899693e-02,  4.68223691e-02, -6.04043417e-02,
        -5.00054099e-03,  2.38911882e-02,  1.31480813e-01,
        -3.89275723e-03,  4.60241437e-02,  1.74435899e-02,
         2.05952320e-02,  3.60550992e-02,  9.18791443e-02,
        -6.16800822e-02,  4.48270999e-02, -1.76441949e-02,
        -4.05909643e-02, -1.60280038e-02, -9.43726897e-02,
        -1.88190006e-02,  1.15899695e-02, -1.98652335e-02,
        -6.94554523e-02,  1.79333892e-02, -1.66503284e-02,
        -1.37450933e-01,  1.88497100e-02,  3.67724017e-04,
        -1.77939946e-03,  1.95623143e-03, -2.89017912e-02,
        -7.72993416e-02,  1.47037013e-02,  1.96735431e-02,
         3.75639722e-02, -5.02137208e-33,  2.65440121e-02,
        -6.02014214e-02, -8.22282806e-02,  6.31356006e-03,
         5.31471446e-02,  1.81801245e-02,  1.98359462e-03,
         3.47931869e-02,  5.63336723e-02,  1.89804640e-02,
        -6.83697388e-02,  4.04112861e-02,  1.67988595e-02,
        -3.85185257e-02,  1.75089613e-02,  4.69552958e-03,
         4.92596067e-02, -2.38829292e-02,  9.91086755e-03,
         2.42136642e-02,  4.20739502e-02,  1.32923918e-02,
        -1.01762138e-01,  6.60063103e-02,  4.98387180e-02,
         9.43690687e-02,  2.89040357e-02, -5.38724437e-02,
        -3.80998589e-02,  8.24041218e-02, -2.48510540e-02,
        -5.46308793e-02,  7.18040466e-02,  1.16899043e-01,
        -3.82299274e-02, -8.16497058e-02, -1.98103972e-02,
        -3.15300822e-02, -2.37901118e-02, -1.17660545e-01,
         6.87080808e-03, -7.71771148e-02, -1.47206429e-02,
         6.28585219e-02, -1.70919728e-02, -2.12398376e-02,
        -4.86072339e-03,  3.39915343e-02,  5.81588643e-03,
         5.95387816e-02, -4.89262007e-02,  3.19775678e-02,
        -3.84087451e-02, -1.11940466e-01, -6.94524543e-03,
        -1.03560695e-02,  1.46950083e-02, -3.06299999e-02,
         6.30714968e-02,  7.17491210e-02,  7.21438462e-03,
        -9.08696000e-03,  2.74718516e-02,  2.34067421e-02,
        -5.93747497e-02,  1.88850369e-02,  2.69549410e-03,
        -9.64754261e-03,  4.66443971e-03, -2.87693962e-02,
         3.93659472e-02,  1.16108410e-01,  4.90928814e-02,
        -8.57379958e-02, -1.83495749e-02,  4.89566103e-02,
        -2.93299854e-02, -8.89592629e-04,  1.98750217e-02,
         3.26355663e-03,  1.11879529e-02, -3.72822061e-02,
         5.84231736e-03,  5.33503816e-02, -6.99476078e-02,
        -1.83363107e-03, -5.38137183e-02,  2.52836607e-02,
        -3.69864702e-02,  4.25823443e-02,  6.75337538e-02,
         9.77035761e-02,  6.45314455e-02,  5.74673805e-03,
        -2.16813311e-02, -1.97127665e-08,  1.05321698e-03,
        -1.61785597e-03, -3.42950076e-02, -9.42623392e-02,
         5.62253781e-02,  5.42417727e-02, -5.78284711e-02,
         1.12742027e-02, -1.60324182e-02, -3.17540951e-02,
         6.68044761e-02,  1.06565235e-02,  8.25182199e-02,
         6.81543350e-02,  5.59056886e-02,  5.61781675e-02,
         2.47669220e-03, -1.38680381e-03,  3.84884253e-02,
         4.76195067e-02, -3.36111672e-02,  4.39393781e-02,
         1.97872296e-02, -2.60502137e-02, -1.45048842e-01,
         2.13356316e-02, -3.45038287e-02, -6.72633946e-02,
         2.34574750e-02,  5.89340366e-02,  5.13147041e-02,
         4.40114923e-02, -7.79528618e-02, -2.24779043e-02,
        -3.93424816e-02, -1.01902351e-01, -3.55974101e-02,
         2.14216411e-02, -2.02380284e-03, -2.58918889e-02,
         7.56045431e-02,  1.60239153e-02,  5.08798249e-02,
        -1.54697718e-02, -2.03186311e-02,  2.86256503e-02,
        -2.34653875e-02, -1.75464526e-01,  6.12319112e-02,
         4.23796736e-02, -5.63388169e-02, -1.40256276e-02,
        -1.17437750e-01,  5.27737662e-03,  8.32754672e-02,
        -3.70514649e-03, -1.51544688e-02,  7.13977148e-04,
        -7.97829926e-02,  4.86245453e-02,  1.51975257e-02,
         3.93463187e-02,  5.14322072e-02,  6.11301884e-02],
       [-8.65146071e-02,  4.87970014e-04,  2.58275997e-02,
        -2.54851785e-02, -4.02856059e-02, -1.53412027e-02,
         1.01375788e-01, -1.41227676e-03, -9.50654224e-03,
        -1.94846559e-02, -1.72058456e-02, -2.17757877e-02,
        -4.03257012e-02,  6.69564456e-02,  5.78451762e-03,
         2.62765922e-02,  8.85186493e-02,  2.81743240e-02,
         5.55344485e-02, -6.44594282e-02,  2.91096363e-02,
        -2.36503258e-02,  7.14528933e-02, -7.04473292e-04,
        -5.34831807e-02,  1.24882879e-02,  1.82459727e-02,
        -1.49866613e-02, -6.96729720e-02, -1.10052088e-02,
         6.35271296e-02,  6.44342825e-02,  1.37557404e-03,
        -3.21486481e-02,  3.95011827e-02,  5.80251478e-02,
         3.15607339e-02, -1.62490401e-02, -4.22180742e-02,
        -2.93205325e-02, -7.31007010e-02,  1.38081089e-02,
        -2.16647573e-02, -4.80494313e-02,  2.64983047e-02,
         1.36583159e-02,  4.80456557e-03, -9.41293687e-02,
         5.33864088e-03,  3.55245396e-02, -4.05929275e-02,
        -2.03910638e-02, -6.61799265e-03, -2.61375122e-02,
        -1.05173420e-02, -2.46859882e-02,  7.05369981e-03,
        -5.97092323e-02,  6.35069236e-02, -3.22448723e-02,
        -4.14601527e-02, -2.82458141e-02,  2.09398102e-02,
        -6.73005963e-03, -4.85503040e-02, -9.94508639e-02,
        -2.43140440e-02,  3.23385261e-02, -2.83288229e-02,
        -6.57572001e-02, -5.13869487e-02, -2.38649920e-02,
         7.92288780e-02,  1.87721327e-02,  2.71445457e-02,
        -1.29949395e-02, -6.91267475e-02, -5.09465337e-02,
        -3.82188894e-02, -1.73210558e-02, -4.46121357e-02,
        -5.74616753e-02, -3.96182276e-02, -6.25535101e-02,
         1.47975963e-02,  1.10391080e-02, -5.86713431e-03,
         2.81217112e-03, -4.53007482e-02,  3.97543013e-02,
        -8.62121060e-02,  1.40785158e-03,  1.33513823e-01,
         1.09438851e-01,  1.45537760e-02, -1.25120031e-02,
         6.87211612e-03, -1.32643446e-01, -6.06527776e-02,
         1.18265059e-02,  2.30016862e-03, -3.70509401e-02,
         6.04497492e-02, -1.17297480e-02,  5.43907098e-02,
        -1.48681486e-02,  1.65818520e-02, -7.85290599e-02,
         7.26124197e-02,  1.61104389e-02,  1.80265587e-02,
        -5.85877374e-02,  5.97903840e-02, -1.35759218e-02,
         8.07081908e-03, -7.22127929e-02, -1.30950026e-02,
        -1.63649414e-02,  1.68310646e-02, -1.17079653e-02,
         1.76956370e-01,  3.70722339e-02,  6.26908690e-02,
         7.61859817e-03,  1.04026571e-02, -3.96158434e-02,
        -3.71581502e-02,  4.70553731e-33,  4.91299992e-03,
         3.19280438e-02,  1.88486818e-02,  5.81201240e-02,
         3.59605625e-02, -7.20248092e-03,  3.67765538e-02,
        -3.37025635e-02, -5.80831431e-02,  2.59538870e-02,
        -5.15155457e-02, -1.59805007e-02, -1.08614333e-01,
         3.83288711e-02, -7.37830773e-02,  2.83896215e-02,
        -1.60052449e-01, -2.73383874e-02,  5.36301807e-02,
         7.59673640e-02, -3.63397561e-02,  5.23770638e-02,
         1.40696401e-02,  3.46963331e-02, -1.75732765e-02,
         1.93521325e-02,  1.84016663e-03, -2.00150236e-02,
         5.99951074e-02,  3.32595743e-02,  7.54078943e-03,
         5.52467033e-02, -1.44662671e-02, -3.93694602e-02,
         5.20756990e-02, -5.51420115e-02, -2.45295209e-03,
        -8.10111687e-02,  7.94949941e-03,  1.13846213e-01,
         1.00186616e-01, -8.84652808e-02, -1.02515161e-01,
         7.06524476e-02, -1.63391680e-02,  6.48059323e-02,
         7.31837973e-02,  4.26917262e-02, -1.76321231e-02,
         7.93698579e-02, -2.19619218e-02,  5.44327311e-03,
        -1.64109617e-02, -6.68743551e-02, -1.11254668e-02,
        -2.76699103e-02,  2.32436489e-02, -1.52804200e-02,
         2.93404255e-02, -5.84293716e-02,  4.83531244e-02,
         2.14222614e-02,  3.39900912e-03, -5.95203899e-02,
        -1.73427165e-02,  4.11798395e-02,  8.15699622e-02,
         7.93752261e-03,  1.15869213e-02, -3.20462044e-03,
         3.46615985e-02, -1.00665297e-02,  6.01208843e-02,
        -8.22284520e-02, -7.19985133e-03, -6.10174984e-02,
         3.55465375e-02, -1.01305488e-02, -5.91859370e-02,
         1.03695067e-02,  1.14206308e-02, -3.80116515e-03,
        -7.93443397e-02,  3.61680868e-04,  1.75351382e-03,
        -1.11067928e-01,  4.27425792e-03, -7.94780552e-02,
        -2.39447877e-02,  1.70891825e-02,  3.75236198e-03,
        -1.02338880e-01,  1.05801062e-03,  6.87778695e-03,
         2.54073218e-02, -5.24231175e-33,  3.68926786e-02,
        -6.90509453e-02, -1.02019921e-01,  2.48257443e-03,
         4.86167632e-02,  7.51736155e-03, -3.83508322e-03,
         3.73655558e-02,  7.86238611e-02,  6.76319078e-02,
        -5.57355396e-02,  6.25605136e-02, -1.64473820e-02,
        -3.29405591e-02,  6.21434599e-02, -3.42712030e-02,
         6.78043887e-02, -1.82595139e-03,  3.17515545e-02,
         3.18168364e-02,  3.32051888e-02,  1.01495665e-02,
        -1.08873248e-01,  4.19783443e-02,  5.92546016e-02,
         8.96404013e-02, -2.79781036e-02, -4.11048271e-02,
        -1.76022798e-02,  7.99060017e-02, -3.10481396e-02,
        -2.95141973e-02,  7.65393823e-02,  7.16927871e-02,
        -3.19607519e-02, -6.39517158e-02, -3.54435891e-02,
        -3.55825946e-02, -5.03244288e-02, -1.15900129e-01,
        -2.83668395e-02, -8.42447430e-02, -1.15767661e-02,
         9.59516019e-02, -1.24734202e-02, -2.62290332e-02,
        -3.01413648e-02,  8.39219764e-02, -5.34593649e-02,
         1.28624486e-02,  2.38519791e-03,  3.17642055e-02,
        -3.08287125e-02, -1.17580526e-01,  3.70922089e-02,
        -7.43459258e-03,  2.90620886e-02, -9.30050574e-03,
         9.29529145e-02,  7.34469220e-02, -1.12509811e-02,
        -3.22453193e-02,  3.77791263e-02,  3.06779556e-02,
        -5.50471321e-02,  8.39541107e-03, -3.43582518e-02,
        -6.01098649e-02,  2.01980118e-03, -7.69354729e-03,
         3.83070149e-02,  1.09309003e-01,  1.99371371e-02,
        -1.22115046e-01, -1.40460795e-02,  9.59536154e-03,
         2.02217903e-02,  5.71524687e-02,  4.59567457e-02,
         1.02109434e-02,  2.50559058e-02, -5.57304767e-04,
         2.45365761e-02,  3.88692133e-02, -2.44650636e-02,
         2.68882383e-02, -8.63522887e-02,  7.36127570e-02,
        -3.18372399e-02,  8.84750634e-02,  5.99031411e-02,
         1.10796228e-01,  4.21412736e-02, -1.04187643e-02,
        -5.33695100e-03, -2.35297293e-08,  1.27651701e-02,
        -2.01397296e-02, -2.55835336e-02, -1.30588636e-01,
         2.58848406e-02,  1.20354788e-02, -4.93872575e-02,
         5.02363630e-02, -4.22813464e-03, -2.39781626e-02,
         9.55426097e-02,  4.66964580e-02,  9.00753215e-02,
         5.78472838e-02,  1.49448374e-02,  5.01941182e-02,
         6.39089243e-03,  2.19863374e-02, -1.52964629e-02,
         5.02107330e-02,  1.83379035e-02,  7.00219125e-02,
         1.18103260e-02, -3.88091356e-02, -1.23932451e-01,
         1.00337276e-02, -1.85230542e-02, -8.86914730e-02,
         5.07451780e-02,  4.59622666e-02,  4.53486070e-02,
         1.39255300e-02, -2.07250081e-02,  1.46993324e-02,
        -6.42463937e-02, -5.80392294e-02, -4.66276072e-02,
         2.80973800e-02, -1.28575936e-02, -6.27827272e-02,
         6.62770821e-03, -1.09304236e-02,  7.57172257e-02,
        -3.26004624e-02, -5.38817309e-02,  2.68185642e-02,
        -5.20705320e-02, -8.59412998e-02,  3.54282521e-02,
         2.19699293e-02, -7.48318881e-02, -2.82116551e-02,
        -1.33067250e-01,  3.39877829e-02,  8.29210877e-02,
         9.44810733e-03, -4.69741412e-02,  4.29990105e-02,
        -4.03988659e-02,  7.50470608e-02,  6.81845024e-02,
         2.06026956e-02,  1.46802096e-02,  4.54443321e-02]], dtype=float32)

Faz a média dos *embeddings* para encontrar os filmes similares

In [34]:
np.mean(embeddings_query, axis=0)

array([-6.92324638e-02,  6.92200731e-04,  1.97593383e-02, -2.16796994e-02,
       -4.88054268e-02, -1.51488278e-03,  1.00793526e-01, -1.20748300e-02,
        3.53812892e-03, -6.62334682e-03, -2.60515418e-03, -1.70853138e-02,
       -1.89814232e-02,  7.08111599e-02,  1.10414475e-02,  2.13854164e-02,
        6.64860606e-02,  3.45265716e-02,  7.45241418e-02, -6.98116124e-02,
        4.76667173e-02, -9.99997091e-03,  6.96889758e-02, -1.06576607e-02,
       -5.46349958e-02,  2.67314985e-02,  7.54536921e-03, -2.26662047e-02,
       -5.29745072e-02, -2.60952730e-02,  7.00346902e-02,  5.89012802e-02,
        9.74311866e-03, -3.43117118e-02,  2.60102004e-02,  3.14724520e-02,
        2.66602542e-02, -3.48419361e-02, -3.13553847e-02, -2.04935297e-03,
       -6.54895157e-02,  1.19180093e-02, -1.58172995e-02, -6.51483759e-02,
        1.60977785e-02,  4.29980410e-03, -1.68463979e-02, -9.07835364e-02,
        3.05366702e-02,  6.14875369e-02, -4.26211357e-02, -2.12162584e-02,
        8.19272641e-03, -7.17176031e-03,  1.31113203e-02, -9.29300673e-04,
       -1.31411268e-03, -6.06819466e-02,  6.39041066e-02, -3.21891420e-02,
       -4.59159687e-02, -1.22655174e-02,  1.72655825e-02,  1.13698272e-02,
       -4.55190986e-02, -1.10517979e-01, -1.58079993e-02, -4.44341451e-04,
       -2.94425450e-02, -6.90395981e-02, -7.62864277e-02, -2.14912388e-02,
        5.32117896e-02, -3.41999345e-03,  9.91017185e-03, -2.47542886e-03,
       -4.70040143e-02, -4.04650867e-02, -3.47073562e-02, -3.08813974e-02,
       -5.03982082e-02, -6.61261305e-02, -1.32435150e-02, -6.29869476e-02,
       -4.16370761e-03,  3.83939669e-02,  3.53256576e-02, -1.50719180e-03,
       -5.12569472e-02,  4.13137972e-02, -8.56220275e-02,  2.13131364e-02,
        1.25829026e-01,  1.05660848e-01,  4.64904867e-03, -1.95024740e-02,
       -4.20171302e-03, -1.27724081e-01, -5.09753190e-02,  1.03454804e-03,
        1.51818730e-02, -4.14646342e-02,  7.49055445e-02, -1.71692763e-02,
        4.55295071e-02,  3.58523289e-03,  1.14737162e-02, -7.32413679e-02,
        6.91953450e-02,  1.11387717e-02,  9.03288461e-03, -3.56142223e-02,
        4.31254804e-02,  7.14216800e-03,  8.07336066e-03, -6.66413009e-02,
       -1.73527468e-03, -2.54553407e-02,  1.13570150e-02,  1.04094716e-03,
        1.69557065e-01,  3.44116911e-02,  3.55608836e-02,  1.70455668e-02,
        5.62264724e-03, -4.71953303e-02, -4.04526889e-02,  4.35854938e-33,
       -1.74835534e-03,  2.95391120e-02,  1.89655572e-02,  3.82372513e-02,
        2.31270418e-02,  1.69053711e-02,  2.56492756e-02, -1.79222133e-02,
       -7.58133084e-02,  8.46392848e-03, -8.87329206e-02,  1.43057890e-02,
       -1.10590741e-01,  1.60189439e-02, -3.22884992e-02, -5.85502014e-03,
       -1.37826040e-01, -2.61184536e-02,  5.92321120e-02,  6.22885972e-02,
       -3.79891619e-02,  5.60931787e-02, -1.62071129e-03,  3.27917114e-02,
       -2.00438146e-02,  3.27504948e-02, -5.85255399e-03, -3.34355980e-02,
        5.32997884e-02,  2.59501562e-02,  7.16259563e-03,  2.05332078e-02,
        1.01205800e-03, -2.44788900e-02,  4.99529429e-02, -4.75192852e-02,
        1.52523918e-02, -6.59994036e-02, -2.12763622e-02,  1.08825497e-01,
        8.27720761e-02, -9.34645683e-02, -8.96580145e-02,  7.95698389e-02,
       -2.49611028e-02,  4.03383076e-02,  7.39048123e-02,  7.89528154e-03,
       -3.56295034e-02,  9.22837555e-02, -3.01841609e-02,  1.15606580e-02,
       -3.53464335e-02, -7.57513940e-02, -2.24644728e-02, -1.61877722e-02,
        1.67740118e-02, -3.58859599e-02,  1.10789519e-02, -4.40016650e-02,
        7.73178190e-02,  2.94561163e-02,  2.51106899e-02, -5.99623658e-02,
       -1.11716287e-02,  3.25355157e-02,  1.06525391e-01,  2.02238280e-03,
        2.88055316e-02,  7.11948471e-03,  2.76284143e-02,  1.29942847e-02,
        7.60000125e-02, -7.19542652e-02,  1.88136250e-02, -3.93308476e-02,
       -2.52221338e-03, -1.30792763e-02, -7.67793134e-02, -4.22474695e-03,
        1.15053002e-02, -1.18331993e-02, -7.43998960e-02,  9.14753508e-03,
       -7.44840736e-03, -1.24259427e-01,  1.15619842e-02, -3.95551659e-02,
       -1.28620937e-02,  9.52270720e-03, -1.25747146e-02, -8.98191109e-02,
        7.88085628e-03,  1.32756652e-02,  3.14856470e-02, -5.13184173e-33,
        3.17183435e-02, -6.46261871e-02, -9.21241045e-02,  4.39806748e-03,
        5.08819520e-02,  1.28487432e-02, -9.25744302e-04,  3.60793695e-02,
        6.74787685e-02,  4.33061868e-02, -6.20526373e-02,  5.14858998e-02,
        1.75738707e-04, -3.57295424e-02,  3.98262106e-02, -1.47878369e-02,
        5.85319996e-02, -1.28544401e-02,  2.08312105e-02,  2.80152503e-02,
        3.76395695e-02,  1.17209796e-02, -1.05317697e-01,  5.39923273e-02,
        5.45466617e-02,  9.20047313e-02,  4.62966040e-04, -4.74886373e-02,
       -2.78510693e-02,  8.11550617e-02, -2.79495977e-02, -4.20725383e-02,
        7.41717145e-02,  9.42959189e-02, -3.50953415e-02, -7.28007108e-02,
       -2.76269931e-02, -3.35563384e-02, -3.70572694e-02, -1.16780341e-01,
       -1.07480157e-02, -8.07109326e-02, -1.31487045e-02,  7.94050619e-02,
       -1.47826970e-02, -2.37344354e-02, -1.75010450e-02,  5.89567572e-02,
       -2.38217395e-02,  3.62006165e-02, -2.32705008e-02,  3.18708867e-02,
       -3.46187279e-02, -1.14760496e-01,  1.50734819e-02, -8.89533106e-03,
        2.18785480e-02, -1.99652538e-02,  7.80122057e-02,  7.25980252e-02,
       -2.01829826e-03, -2.06661392e-02,  3.26254889e-02,  2.70423479e-02,
       -5.72109409e-02,  1.36402240e-02, -1.58313792e-02, -3.48787047e-02,
        3.34212044e-03, -1.82314720e-02,  3.88364792e-02,  1.12708703e-01,
        3.45150083e-02, -1.03926525e-01, -1.61978267e-02,  2.92759854e-02,
       -4.55409754e-03,  2.81314384e-02,  3.29158828e-02,  6.73724990e-03,
        1.81219298e-02, -1.89197548e-02,  1.51894465e-02,  4.61097956e-02,
       -4.72063348e-02,  1.25273038e-02, -7.00830072e-02,  4.94482070e-02,
       -3.44118550e-02,  6.55287057e-02,  6.37184456e-02,  1.04249902e-01,
        5.33363596e-02, -2.33601313e-03, -1.35091413e-02, -2.16212470e-08,
        6.90919347e-03, -1.08787930e-02, -2.99392715e-02, -1.12425491e-01,
        4.10551094e-02,  3.31386253e-02, -5.36078662e-02,  3.07552833e-02,
       -1.01302769e-02, -2.78661288e-02,  8.11735392e-02,  2.86764912e-02,
        8.62967670e-02,  6.30008131e-02,  3.54252644e-02,  5.31861410e-02,
        4.43379208e-03,  1.02997664e-02,  1.15959812e-02,  4.89151180e-02,
       -7.63663184e-03,  5.69806471e-02,  1.57987773e-02, -3.24296728e-02,
       -1.34490639e-01,  1.56846792e-02, -2.65134424e-02, -7.79774338e-02,
        3.71013284e-02,  5.24481535e-02,  4.83316556e-02,  2.89685111e-02,
       -4.93389368e-02, -3.88928596e-03, -5.17944396e-02, -7.99707919e-02,
       -4.11125086e-02,  2.47595105e-02, -7.44069833e-03, -4.43373099e-02,
        4.11161259e-02,  2.54674582e-03,  6.32985234e-02, -2.40351167e-02,
       -3.71001810e-02,  2.77221072e-02, -3.77679616e-02, -1.30702913e-01,
        4.83300835e-02,  3.21748033e-02, -6.55853525e-02, -2.11186409e-02,
       -1.25252500e-01,  1.96325798e-02,  8.30982774e-02,  2.87148030e-03,
       -3.10643055e-02,  2.18564942e-02, -6.00909293e-02,  6.18358031e-02,
        4.16910127e-02,  2.99745072e-02,  3.30562070e-02,  5.32872602e-02],
      dtype=float32)

### Função para retornar a recomendação baseada em conteúdo

In [35]:
def content_based_recommendation(movie_ids=[], topN=10):

    ranking = []
    embeddings_query = model.encode(retorna_documentos(movies.query('movieId in ' + str(movie_ids))))
    if len(movie_ids) > 1: embeddings_query = np.mean(embeddings_query, axis=0)

    labels, distances = index.knn_query(embeddings_query, k=topN*2)
    for idx,(doc_id, dist) in enumerate(zip(labels[0], distances[0])):
        if (movies.index.values[doc_id] not in movie_ids):
            ranking.append( list(movies.iloc[doc_id][['title', 'genres', 'tags', 'imdb_score']].values) + [idx, 1-dist] )

    aux = pd.DataFrame(ranking, columns=['title', 'genres', 'tags', 'imdb_score', 'rank_pos', 'rank_score'])
    return aux.sort_values(by=['rank_score', 'imdb_score'], ascending=False).head(topN)

content_based_recommendation([1])

,title,genres,tags,imdb_score,rank_pos,rank_score
0,Toy Story 3,Adventure|Animation|Children|Comedy|Fantasy|IMAX,,3.990032,1,0.853986
1,Toy Story 2,Adventure|Animation|Children|Comedy|Fantasy,tom_hanks original pixar animation disney funn...,3.810019,2,0.847664
2,The Lego Movie,Action|Adventure|Animation|Children|Comedy|Fan...,colorful feel-good quirky fun clever cheeky im...,3.734051,3,0.837530
3,Turbo,Adventure|Animation|Children|Comedy|Fantasy,,3.186203,4,0.821473
4,"Wild, The",Adventure|Animation|Children|Comedy|Fantasy,,3.186203,5,0.815881
5,"Bug's Life, A",Adventure|Animation|Children|Comedy,pixar,3.493684,6,0.814950
6,Antz,Adventure|Animation|Children|Comedy|Fantasy,,3.247445,7,0.810395
7,"Monsters, Inc.",Adventure|Animation|Children|Comedy|Fantasy,,3.832355,8,0.801546
8,Toys,Comedy|Fantasy,,2.650415,9,0.791271
9,Robots,Adventure|Animation|Children|Comedy|Fantasy|Sc...,,3.102216,10,0.789724

In [36]:
ids = [1, 108932]
retorna_documentos(movies.query('movieId in ' + str(ids)))

['toy story adventure animation children comedy fantasy fun pixar',
 'the lego movie action adventure animation children comedy fantasy colorful feel good quirky fun clever cheeky imaginative']

In [37]:
content_based_recommendation([1, 108932])

,title,genres,tags,imdb_score,rank_pos,rank_score
0,Turbo,Adventure|Animation|Children|Comedy|Fantasy,,3.186203,2,0.855695
1,Toy Story 3,Adventure|Animation|Children|Comedy|Fantasy|IMAX,,3.990032,3,0.851180
2,"Wild, The",Adventure|Animation|Children|Comedy|Fantasy,,3.186203,4,0.842802
3,Antz,Adventure|Animation|Children|Comedy|Fantasy,,3.247445,5,0.842397
4,"Monsters, Inc.",Adventure|Animation|Children|Comedy|Fantasy,,3.832355,6,0.822548
5,Toy Story 2,Adventure|Animation|Children|Comedy|Fantasy,tom_hanks original pixar animation disney funn...,3.810019,7,0.821488
6,Home,Adventure|Animation|Children|Comedy|Fantasy|Sc...,,3.256590,8,0.815789
7,Ice Age,Adventure|Animation|Children|Comedy,,3.647468,9,0.808273
8,"Bug's Life, A",Adventure|Animation|Children|Comedy,pixar,3.493684,10,0.808222
9,Robots,Adventure|Animation|Children|Comedy|Fantasy|Sc...,,3.102216,11,0.805389

In [38]:
ids = [858]
retorna_documentos(movies.query('movieId in ' + str(ids)))

['godfather the crime drama mafia']

In [39]:
content_based_recommendation([858])

,title,genres,tags,imdb_score,rank_pos,rank_score
0,"Godfather: Part II, The",Crime|Drama,al_pacino mafia,4.194652,1,0.821600
1,Casino,Crime|Drama,mafia,3.861121,2,0.768495
2,Donnie Brasco,Crime|Drama,mafia,3.669869,3,0.749043
3,Gangster Squad,Action|Crime|Drama,,3.280170,4,0.745306
4,"Godfather: Part III, The",Crime|Drama|Mystery|Thriller,mafia classic andy_garcia francis_ford_coppola...,3.340038,5,0.736036
5,Goodfellas,Crime|Drama,mafia,4.184163,6,0.735513
6,Carlito's Way,Crime|Drama,al_pacino gangster mafia,3.654158,7,0.692946
7,Miller's Crossing,Crime|Drama|Film-Noir|Thriller,mafia,3.926277,8,0.680292
8,Scarface,Crime|Drama,,3.351094,9,0.679608
9,Gangster No. 1,Action|Crime|Thriller,,3.196836,10,0.678310